"""initial baseline schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-06-21 17:29:28.743297
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy.vector
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pgvector extension must exist before the VECTOR columns below are created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_norm', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('arxiv_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_papers_source_extid')
    )
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=False)
    op.create_index(op.f('ix_papers_citation_count'), 'papers', ['citation_count'], unique=False)
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.create_index(op.f('ix_papers_external_id'), 'papers', ['external_id'], unique=False)
    op.create_index(op.f('ix_papers_source'), 'papers', ['source'], unique=False)
    op.create_index('ix_papers_title_norm', 'papers', ['title_norm'], unique=False)
    op.create_index(op.f('ix_papers_year'), 'papers', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('extractions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_paper_id'), 'extractions', ['paper_id'], unique=True)
    op.create_table('landscapes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('synthesis', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landscapes_status'), 'landscapes', ['status'], unique=False)
    op.create_index(op.f('ix_landscapes_user_id'), 'landscapes', ['user_id'], unique=False)
    op.create_table('paper_pdfs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('parsed_markdown', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_pdfs_paper_id'), 'paper_pdfs', ['paper_id'], unique=True)
    op.create_index(op.f('ix_paper_pdfs_status'), 'paper_pdfs', ['status'], unique=False)
    op.create_table('paper_sections',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('heading', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_sections_paper_id'), 'paper_sections', ['paper_id'], unique=False)
    op.create_index('ix_section_paper_ord', 'paper_sections', ['paper_id', 'ordinal'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('section_heading', sa.Text(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['paper_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunk_paper_ord', 'chunks', ['paper_id', 'ordinal'], unique=False)
    op.create_index(op.f('ix_chunks_paper_id'), 'chunks', ['paper_id'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('landscape_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_landscape_id'), 'clusters', ['landscape_id'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('landscape_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('term', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('short_definition', sa.Text(), nullable=True),
    sa.Column('long_definition', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('related_terms', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('paper_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('source_grounding', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('landscape_id', 'name', name='uq_concept')
    )
    op.create_index(op.f('ix_concepts_landscape_id'), 'concepts', ['landscape_id'], unique=False)
    op.create_index(op.f('ix_concepts_slug'), 'concepts', ['slug'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('landscape_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('front', sa.Text(), nullable=True),
    sa.Column('back', sa.Text(), nullable=True),
    sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('concept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_landscape_id'), 'flashcards', ['landscape_id'], unique=False)
    op.create_table('obsidian_exports',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('landscape_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commit_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pushed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obsidian_exports_content_hash'), 'obsidian_exports', ['content_hash'], unique=False)
    op.create_index(op.f('ix_obsidian_exports_landscape_id'), 'obsidian_exports', ['landscape_id'], unique=False)
    op.create_table('paper_relationships',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('landscape_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('src_paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dst_paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dst_paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], ),
    sa.ForeignKeyConstraint(['src_paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_relationships_dst_paper_id'), 'paper_relationships', ['dst_paper_id'], unique=False)
    op.create_index(op.f('ix_paper_relationships_kind'), 'paper_relationships', ['kind'], unique=False)
    op.create_index(op.f('ix_paper_relationships_landscape_id'), 'paper_relationships', ['landscape_id'], unique=False)
    op.create_index(op.f('ix_paper_relationships_src_paper_id'), 'paper_relationships', ['src_paper_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('landscape_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('concept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_landscape_id'), 'quizzes', ['landscape_id'], unique=False)
    op.create_table('review_attempts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('landscape_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_attempts_item_id'), 'review_attempts', ['item_id'], unique=False)
    op.create_index(op.f('ix_review_attempts_landscape_id'), 'review_attempts', ['landscape_id'], unique=False)
    op.create_table('search_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('landscape_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_jobs_landscape_id'), 'search_jobs', ['landscape_id'], unique=False)
    op.create_index(op.f('ix_search_jobs_stage'), 'search_jobs', ['stage'], unique=False)
    op.create_table('cluster_papers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cluster_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'paper_id', name='uq_cp')
    )
    op.create_index(op.f('ix_cluster_papers_cluster_id'), 'cluster_papers', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_papers_paper_id'), 'cluster_papers', ['paper_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['search_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_index('ix_job_events_job_seq', 'job_events', ['job_id', 'seq'], unique=False)
    op.create_index(op.f('ix_job_events_seq'), 'job_events', ['seq'], unique=True)
    op.create_index(op.f('ix_job_events_stage'), 'job_events', ['stage'], unique=False)
    op.create_table('landscape_papers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('landscape_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('cluster_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reading_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('landscape_id', 'paper_id', name='uq_lp')
    )
    op.create_index(op.f('ix_landscape_papers_category'), 'landscape_papers', ['category'], unique=False)
    op.create_index(op.f('ix_landscape_papers_cluster_id'), 'landscape_papers', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_landscape_papers_landscape_id'), 'landscape_papers', ['landscape_id'], unique=False)
    op.create_index(op.f('ix_landscape_papers_paper_id'), 'landscape_papers', ['paper_id'], unique=False)
    op.create_index(op.f('ix_landscape_papers_reading_order'), 'landscape_papers', ['reading_order'], unique=False)
    op.create_index(op.f('ix_landscape_papers_score'), 'landscape_papers', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landscape_papers_score'), table_name='landscape_papers')
    op.drop_index(op.f('ix_landscape_papers_reading_order'), table_name='landscape_papers')
    op.drop_index(op.f('ix_landscape_papers_paper_id'), table_name='landscape_papers')
    op.drop_index(op.f('ix_landscape_papers_landscape_id'), table_name='landscape_papers')
    op.drop_index(op.f('ix_landscape_papers_cluster_id'), table_name='landscape_papers')
    op.drop_index(op.f('ix_landscape_papers_category'), table_name='landscape_papers')
    op.drop_table('landscape_papers')
    op.drop_index(op.f('ix_job_events_stage'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_seq'), table_name='job_events')
    op.drop_index('ix_job_events_job_seq', table_name='job_events')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_cluster_papers_paper_id'), table_name='cluster_papers')
    op.drop_index(op.f('ix_cluster_papers_cluster_id'), table_name='cluster_papers')
    op.drop_table('cluster_papers')
    op.drop_index(op.f('ix_search_jobs_stage'), table_name='search_jobs')
    op.drop_index(op.f('ix_search_jobs_landscape_id'), table_name='search_jobs')
    op.drop_table('search_jobs')
    op.drop_index(op.f('ix_review_attempts_landscape_id'), table_name='review_attempts')
    op.drop_index(op.f('ix_review_attempts_item_id'), table_name='review_attempts')
    op.drop_table('review_attempts')
    op.drop_index(op.f('ix_quizzes_landscape_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_paper_relationships_src_paper_id'), table_name='paper_relationships')
    op.drop_index(op.f('ix_paper_relationships_landscape_id'), table_name='paper_relationships')
    op.drop_index(op.f('ix_paper_relationships_kind'), table_name='paper_relationships')
    op.drop_index(op.f('ix_paper_relationships_dst_paper_id'), table_name='paper_relationships')
    op.drop_table('paper_relationships')
    op.drop_index(op.f('ix_obsidian_exports_landscape_id'), table_name='obsidian_exports')
    op.drop_index(op.f('ix_obsidian_exports_content_hash'), table_name='obsidian_exports')
    op.drop_table('obsidian_exports')
    op.drop_index(op.f('ix_flashcards_landscape_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_concepts_slug'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_landscape_id'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_clusters_landscape_id'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_chunks_paper_id'), table_name='chunks')
    op.drop_index('ix_chunk_paper_ord', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_section_paper_ord', table_name='paper_sections')
    op.drop_index(op.f('ix_paper_sections_paper_id'), table_name='paper_sections')
    op.drop_table('paper_sections')
    op.drop_index(op.f('ix_paper_pdfs_status'), table_name='paper_pdfs')
    op.drop_index(op.f('ix_paper_pdfs_paper_id'), table_name='paper_pdfs')
    op.drop_table('paper_pdfs')
    op.drop_index(op.f('ix_landscapes_user_id'), table_name='landscapes')
    op.drop_index(op.f('ix_landscapes_status'), table_name='landscapes')
    op.drop_table('landscapes')
    op.drop_index(op.f('ix_extractions_paper_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_papers_year'), table_name='papers')
    op.drop_index('ix_papers_title_norm', table_name='papers')
    op.drop_index(op.f('ix_papers_source'), table_name='papers')
    op.drop_index(op.f('ix_papers_external_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_index(op.f('ix_papers_citation_count'), table_name='papers')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
