"""review states (FSRS scheduling)

Revision ID: 0005_review_states
Revises: 0004_runtime_settings
Create Date: 2026-06-22 17:26:10.216510
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


revision = '0005_review_states'
down_revision = '0004_runtime_settings'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_states',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('landscape_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('due', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['landscape_id'], ['landscapes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_kind', 'item_id', name='uq_review_state')
    )
    op.create_index('ix_review_state_due', 'review_states', ['user_id', 'due'], unique=False)
    op.create_index(op.f('ix_review_states_due'), 'review_states', ['due'], unique=False)
    op.create_index(op.f('ix_review_states_item_id'), 'review_states', ['item_id'], unique=False)
    op.create_index(op.f('ix_review_states_landscape_id'), 'review_states', ['landscape_id'], unique=False)
    op.create_index(op.f('ix_review_states_user_id'), 'review_states', ['user_id'], unique=False)
    op.add_column('review_attempts', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_review_attempts_user_id'), 'review_attempts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'review_attempts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_attempts', type_='foreignkey')
    op.drop_index(op.f('ix_review_attempts_user_id'), table_name='review_attempts')
    op.drop_column('review_attempts', 'user_id')
    op.drop_index(op.f('ix_review_states_user_id'), table_name='review_states')
    op.drop_index(op.f('ix_review_states_landscape_id'), table_name='review_states')
    op.drop_index(op.f('ix_review_states_item_id'), table_name='review_states')
    op.drop_index(op.f('ix_review_states_due'), table_name='review_states')
    op.drop_index('ix_review_state_due', table_name='review_states')
    op.drop_table('review_states')
    # ### end Alembic commands ###
